### ISSUE TITLE
Add a function to apply a tactic to subgoals within a certain range

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-dependent-lcf#34]
This is to create an auto tactic that repeatedly applies the auto-step tactic in a certain range. So far these ranges are needed:

- apply tac to everything before n
- apply tac to everything after n

**Comment by jonsterling** [comment]
I keep forgetting to do this! I'm slammed today, but I will try to do it soon

**Comment by favonia** [comment]
Updated with what showed up in practice.

**Comment by jonsterling** [comment]
`apply tac to everything before n` can be achieved already using `List.tabulate`. But we need special support for the other one.
